/* automatically generated from xfce4-notifyd-config/xfce4-notifyd-config.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfce4_notifyd_config_ui)
#endif
#ifdef __GNUC__
static const char xfce4_notifyd_config_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfce4_notifyd_config_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!-- Generated with glade 3"
  ".18.3 -->\n<interface>\n  <requires lib=\"gtk+\" version=\"3.14\"/>\n  "
  "<requires lib=\"libxfce4ui-2\" version=\"4.12\"/>\n  <object class=\"Gt"
  "kAdjustment\" id=\"adjustment1\">\n    <property name=\"lower\">1</prop"
  "erty>\n    <property name=\"upper\">480</property>\n    <property name="
  "\"value\">10</property>\n    <property name=\"step_increment\">1</prope"
  "rty>\n    <property name=\"page_increment\">10</property>\n  </object>\n"
  "  <object class=\"GtkAdjustment\" id=\"adjustment2\">\n    <property na"
  "me=\"upper\">1.01</property>\n    <property name=\"value\">0.9000000000"
  "0000002</property>\n    <property name=\"step_increment\">0.01</propert"
  "y>\n    <property name=\"page_increment\">0.10000000000000001</property"
  ">\n    <property name=\"page_size\">0.01</property>\n  </object>\n  <ob"
  "ject class=\"GtkListStore\" id=\"model1\">\n    <columns>\n      <!-- c"
  "olumn-name gchararray -->\n      <column type=\"gchararray\"/>\n    </c"
  "olumns>\n    <data>\n      <row>\n        <col id=\"0\" translatable=\""
  "yes\">Top left</col>\n      </row>\n      <row>\n        <col id=\"0\" "
  "translatable=\"yes\">Bottom left</col>\n      </row>\n      <row>\n    "
  "    <col id=\"0\" translatable=\"yes\">Top right</col>\n      </row>\n "
  "     <row>\n        <col id=\"0\" translatable=\"yes\">Bottom right</co"
  "l>\n      </row>\n    </data>\n  </object>\n  <object class=\"XfceTitle"
  "dDialog\" id=\"notifyd_settings_dlg\">\n    <property name=\"can_focus\""
  ">False</property>\n    <property name=\"title\" translatable=\"yes\">No"
  "tifications</property>\n    <property name=\"window_position\">center-o"
  "n-parent</property>\n    <property name=\"default_width\">500</property"
  ">\n    <property name=\"default_height\">500</property>\n    <property "
  "name=\"icon_name\">xfce4-notifyd</property>\n    <property name=\"type_"
  "hint\">dialog</property>\n    <property name=\"subtitle\" translatable="
  "\"yes\">Customize how notifications appear on your screen</property>\n "
  "   <child internal-child=\"vbox\">\n      <object class=\"GtkBox\" id=\""
  "dialog-vbox1\">\n        <property name=\"visible\">True</property>\n  "
  "      <property name=\"can_focus\">False</property>\n        <property "
  "name=\"orientation\">vertical</property>\n        <property name=\"spac"
  "ing\">2</property>\n        <child internal-child=\"action_area\">\n   "
  "       <object class=\"GtkButtonBox\" id=\"dialog-action_area1\">\n    "
  "        <property name=\"visible\">True</property>\n            <proper"
  "ty name=\"can_focus\">False</property>\n            <property name=\"he"
  "xpand\">True</property>\n            <property name=\"homogeneous\">Tru"
  "e</property>\n            <child>\n              <object class=\"GtkBut"
  "ton\" id=\"help_btn\">\n                <property name=\"label\">gtk-he"
  "lp</property>\n                <property name=\"visible\">True</propert"
  "y>\n                <property name=\"can_focus\">True</property>\n     "
  "           <property name=\"receives_default\">True</property>\n       "
  "         <property name=\"use_stock\">True</property>\n              </"
  "object>\n              <packing>\n                <property name=\"expa"
  "nd\">False</property>\n                <property name=\"fill\">False</p"
  "roperty>\n                <property name=\"position\">0</property>\n   "
  "             <property name=\"secondary\">True</property>\n            "
  "  </packing>\n            </child>\n            <child>\n              "
  "<object class=\"GtkButton\" id=\"close_btn\">\n                <propert"
  "y name=\"label\">gtk-close</property>\n                <property name=\""
  "use_action_appearance\">False</property>\n                <property nam"
  "e=\"visible\">True</property>\n                <property name=\"can_foc"
  "us\">True</property>\n                <property name=\"receives_default"
  "\">True</property>\n                <property name=\"use_stock\">True</"
  "property>\n              </object>\n              <packing>\n          "
  "      <property name=\"expand\">True</property>\n                <prope"
  "rty name=\"fill\">True</property>\n                <property name=\"pac"
  "k_type\">end</property>\n                <property name=\"position\">1<"
  "/property>\n              </packing>\n            </child>\n          <"
  "/object>\n          <packing>\n            <property name=\"expand\">Tr"
  "ue</property>\n            <property name=\"fill\">True</property>\n   "
  "         <property name=\"position\">0</property>\n          </packing>"
  "\n        </child>\n        <child>\n          <object class=\"GtkBox\""
  " id=\"plug-child\">\n            <property name=\"visible\">True</prope"
  "rty>\n            <property name=\"can_focus\">False</property>\n      "
  "      <property name=\"border_width\">6</property>\n            <child>"
  "\n              <object class=\"GtkNotebook\" id=\"notebook1\">\n      "
  "          <property name=\"visible\">True</property>\n                <"
  "property name=\"can_focus\">True</property>\n                <child>\n "
  "                 <object class=\"GtkGrid\" id=\"grid1\">\n             "
  "       <property name=\"visible\">True</property>\n                    "
  "<property name=\"can_focus\">False</property>\n                    <pro"
  "perty name=\"margin_left\">12</property>\n                    <property"
  " name=\"margin_right\">12</property>\n                    <property nam"
  "e=\"margin_top\">12</property>\n                    <property name=\"ma"
  "rgin_bottom\">12</property>\n                    <property name=\"row_s"
  "pacing\">6</property>\n                    <property name=\"column_spac"
  "ing\">12</property>\n                    <property name=\"column_homoge"
  "neous\">True</property>\n                    <child>\n                 "
  "     <object class=\"GtkScale\" id=\"opacity_slider\">\n               "
  "         <property name=\"visible\">True</property>\n                  "
  "      <property name=\"can_focus\">True</property>\n                   "
  "     <property name=\"adjustment\">adjustment2</property>\n            "
  "            <property name=\"round_digits\">2</property>\n             "
  "           <property name=\"digits\">2</property>\n                    "
  "    <property name=\"value_pos\">right</property>\n                    "
  "  </object>\n                      <packing>\n                        <"
  "property name=\"left_attach\">1</property>\n                        <pr"
  "operty name=\"top_attach\">3</property>\n                      </packin"
  "g>\n                    </child>\n                    <child>\n        "
  "              <object class=\"GtkButton\" id=\"preview_button\">\n     "
  "                   <property name=\"label\" translatable=\"yes\">Show N"
  "otification _Preview</property>\n                        <property name"
  "=\"use_action_appearance\">False</property>\n                        <p"
  "roperty name=\"visible\">True</property>\n                        <prop"
  "erty name=\"can_focus\">True</property>\n                        <prope"
  "rty name=\"receives_default\">True</property>\n                        "
  "<property name=\"use_underline\">True</property>\n                     "
  " </object>\n                      <packing>\n                        <p"
  "roperty name=\"left_attach\">0</property>\n                        <pro"
  "perty name=\"top_attach\">4</property>\n                        <proper"
  "ty name=\"width\">2</property>\n                      </packing>\n     "
  "               </child>\n                    <child>\n                 "
  "     <object class=\"GtkLabel\" id=\"label5\">\n                       "
  " <property name=\"visible\">True</property>\n                        <p"
  "roperty name=\"can_focus\">False</property>\n                        <p"
  "roperty name=\"label\" translatable=\"yes\">_Theme:</property>\n       "
  "                 <property name=\"use_underline\">True</property>\n    "
  "                    <property name=\"xalign\">0</property>\n           "
  "           </object>\n                      <packing>\n                "
  "        <property name=\"left_attach\">0</property>\n                  "
  "      <property name=\"top_attach\">0</property>\n                     "
  " </packing>\n                    </child>\n                    <child>\n"
  "                      <object class=\"GtkComboBox\" id=\"theme_combo\">"
  "\n                        <property name=\"visible\">True</property>\n "
  "                       <property name=\"can_focus\">False</property>\n "
  "                       <child>\n                          <object class"
  "=\"GtkCellRendererText\" id=\"renderer2\"/>\n                          "
  "<attributes>\n                            <attribute name=\"text\">0</a"
  "ttribute>\n                          </attributes>\n                   "
  "     </child>\n                      </object>\n                      <"
  "packing>\n                        <property name=\"left_attach\">1</pro"
  "perty>\n                        <property name=\"top_attach\">0</proper"
  "ty>\n                      </packing>\n                    </child>\n  "
  "                  <child>\n                      <object class=\"GtkLab"
  "el\" id=\"label3\">\n                        <property name=\"visible\""
  ">True</property>\n                        <property name=\"can_focus\">"
  "False</property>\n                        <property name=\"label\" tran"
  "slatable=\"yes\">Default _position:</property>\n                       "
  " <property name=\"use_underline\">True</property>\n                    "
  "    <property name=\"xalign\">0</property>\n                      </obj"
  "ect>\n                      <packing>\n                        <propert"
  "y name=\"left_attach\">0</property>\n                        <property "
  "name=\"top_attach\">1</property>\n                      </packing>\n   "
  "                 </child>\n                    <child>\n               "
  "       <object class=\"GtkComboBox\" id=\"position_combo\">\n          "
  "              <property name=\"visible\">True</property>\n             "
  "           <property name=\"can_focus\">False</property>\n             "
  "           <property name=\"model\">model1</property>\n                "
  "        <child>\n                          <object class=\"GtkCellRende"
  "rerText\" id=\"renderer1\"/>\n                          <attributes>\n "
  "                           <attribute name=\"text\">0</attribute>\n    "
  "                      </attributes>\n                        </child>\n"
  "                      </object>\n                      <packing>\n     "
  "                   <property name=\"left_attach\">1</property>\n       "
  "                 <property name=\"top_attach\">1</property>\n          "
  "            </packing>\n                    </child>\n                 "
  "   <child>\n                      <object class=\"GtkBox\" id=\"hbox4\""
  ">\n                        <property name=\"visible\">True</property>\n"
  "                        <property name=\"can_focus\">False</property>\n"
  "                        <property name=\"spacing\">6</property>\n      "
  "                  <child>\n                          <object class=\"Gt"
  "kSpinButton\" id=\"expire_timeout_sbtn\">\n                            "
  "<property name=\"visible\">True</property>\n                           "
  " <property name=\"can_focus\">True</property>\n                        "
  "    <property name=\"invisible_char\">\342\227\217</property>\n        "
  "                    <property name=\"primary_icon_activatable\">False</"
  "property>\n                            <property name=\"secondary_icon_"
  "activatable\">False</property>\n                            <property n"
  "ame=\"adjustment\">adjustment1</property>\n                            "
  "<property name=\"numeric\">True</property>\n                          <"
  "/object>\n                          <packing>\n                        "
  "    <property name=\"expand\">False</property>\n                       "
  "     <property name=\"fill\">False</property>\n                        "
  "    <property name=\"position\">0</property>\n                         "
  " </packing>\n                        </child>\n                        "
  "<child>\n                          <object class=\"GtkLabel\" id=\"labe"
  "l4\">\n                            <property name=\"visible\">True</pro"
  "perty>\n                            <property name=\"can_focus\">False<"
  "/property>\n                            <property name=\"label\" transl"
  "atable=\"yes\">seconds</property>\n                            <propert"
  "y name=\"xalign\">0</property>\n                          </object>\n  "
  "                        <packing>\n                            <propert"
  "y name=\"expand\">True</property>\n                            <propert"
  "y name=\"fill\">True</property>\n                            <property "
  "name=\"pack_type\">end</property>\n                            <propert"
  "y name=\"position\">1</property>\n                          </packing>\n"
  "                        </child>\n                      </object>\n    "
  "                  <packing>\n                        <property name=\"l"
  "eft_attach\">1</property>\n                        <property name=\"top"
  "_attach\">2</property>\n                      </packing>\n             "
  "       </child>\n                    <child>\n                      <ob"
  "ject class=\"GtkLabel\" id=\"label1\">\n                        <proper"
  "ty name=\"visible\">True</property>\n                        <property "
  "name=\"can_focus\">False</property>\n                        <property "
  "name=\"label\" translatable=\"yes\">_Disappear after:</property>\n     "
  "                   <property name=\"use_underline\">True</property>\n  "
  "                      <property name=\"mnemonic_widget\">expire_timeout"
  "_sbtn</property>\n                        <property name=\"xalign\">0</"
  "property>\n                      </object>\n                      <pack"
  "ing>\n                        <property name=\"left_attach\">0</propert"
  "y>\n                        <property name=\"top_attach\">2</property>\n"
  "                      </packing>\n                    </child>\n       "
  "             <child>\n                      <object class=\"GtkLabel\" "
  "id=\"label2\">\n                        <property name=\"visible\">True"
  "</property>\n                        <property name=\"can_focus\">False"
  "</property>\n                        <property name=\"label\" translata"
  "ble=\"yes\">_Opacity:</property>\n                        <property nam"
  "e=\"use_underline\">True</property>\n                        <property "
  "name=\"xalign\">0</property>\n                      </object>\n        "
  "              <packing>\n                        <property name=\"left_"
  "attach\">0</property>\n                        <property name=\"top_att"
  "ach\">3</property>\n                      </packing>\n                 "
  "   </child>\n                  </object>\n                </child>\n   "
  "             <child type=\"tab\">\n                  <object class=\"Gt"
  "kLabel\" id=\"label6\">\n                    <property name=\"visible\""
  ">True</property>\n                    <property name=\"can_focus\">Fals"
  "e</property>\n                    <property name=\"label\" translatable"
  "=\"yes\">Appearance</property>\n                  </object>\n          "
  "        <packing>\n                    <property name=\"tab_fill\">Fals"
  "e</property>\n                  </packing>\n                </child>\n "
  "               <child>\n                  <object class=\"GtkGrid\" id="
  "\"grid2\">\n                    <property name=\"visible\">True</proper"
  "ty>\n                    <property name=\"can_focus\">False</property>\n"
  "                    <property name=\"margin_left\">12</property>\n     "
  "               <property name=\"margin_right\">12</property>\n         "
  "           <property name=\"margin_top\">12</property>\n               "
  "     <property name=\"margin_bottom\">12</property>\n                  "
  "  <child>\n                      <object class=\"GtkSwitch\" id=\"do_no"
  "t_disturb\">\n                        <property name=\"visible\">True</"
  "property>\n                        <property name=\"can_focus\">True</p"
  "roperty>\n                      </object>\n                      <packi"
  "ng>\n                        <property name=\"left_attach\">1</property"
  ">\n                        <property name=\"top_attach\">0</property>\n"
  "                      </packing>\n                    </child>\n       "
  "             <child>\n                      <object class=\"GtkLabel\" "
  "id=\"label8\">\n                        <property name=\"visible\">True"
  "</property>\n                        <property name=\"can_focus\">False"
  "</property>\n                        <property name=\"hexpand\">True</p"
  "roperty>\n                        <property name=\"label\" translatable"
  "=\"yes\">Do not disturb</property>\n                        <property n"
  "ame=\"xalign\">0</property>\n                      </object>\n         "
  "             <packing>\n                        <property name=\"left_a"
  "ttach\">0</property>\n                        <property name=\"top_atta"
  "ch\">0</property>\n                      </packing>\n                  "
  "  </child>\n                    <child>\n                      <object "
  "class=\"GtkLabel\" id=\"label9\">\n                        <property na"
  "me=\"visible\">True</property>\n                        <property name="
  "\"can_focus\">False</property>\n                        <property name="
  "\"margin_top\">12</property>\n                        <property name=\""
  "margin_bottom\">6</property>\n                        <property name=\""
  "hexpand\">True</property>\n                        <property name=\"lab"
  "el\" translatable=\"yes\">&lt;b&gt;Show notifications for&lt;/b&gt;</pr"
  "operty>\n                        <property name=\"use_markup\">True</pr"
  "operty>\n                        <property name=\"xalign\">0</property>"
  "\n                      </object>\n                      <packing>\n   "
  "                     <property name=\"left_attach\">0</property>\n     "
  "                   <property name=\"top_attach\">2</property>\n        "
  "                <property name=\"width\">2</property>\n                "
  "      </packing>\n                    </child>\n                    <ch"
  "ild>\n                      <object class=\"GtkRevealer\" id=\"do_not_d"
  "isturb_info\">\n                        <property name=\"visible\">True"
  "</property>\n                        <property name=\"can_focus\">False"
  "</property>\n                        <property name=\"margin_top\">6</p"
  "roperty>\n                        <property name=\"margin_bottom\">12</"
  "property>\n                        <property name=\"transition_type\">n"
  "one</property>\n                        <property name=\"reveal_child\""
  ">True</property>\n                        <child>\n                    "
  "      <object class=\"GtkInfoBar\" id=\"infobar1\">\n                  "
  "          <property name=\"visible\">True</property>\n                 "
  "           <property name=\"app_paintable\">True</property>\n          "
  "                  <property name=\"can_focus\">False</property>\n      "
  "                      <child internal-child=\"action_area\">\n         "
  "                     <object class=\"GtkButtonBox\" id=\"infobar-action"
  "_area1\">\n                                <property name=\"can_focus\""
  ">False</property>\n                                <property name=\"spa"
  "cing\">6</property>\n                                <property name=\"l"
  "ayout_style\">start</property>\n                                <child>"
  "\n                                  <placeholder/>\n                   "
  "             </child>\n                              </object>\n       "
  "                       <packing>\n                                <prop"
  "erty name=\"expand\">True</property>\n                                <"
  "property name=\"fill\">True</property>\n                               "
  " <property name=\"position\">0</property>\n                            "
  "  </packing>\n                            </child>\n                   "
  "         <child internal-child=\"content_area\">\n                     "
  "         <object class=\"GtkBox\" id=\"infobar-content_area1\">\n      "
  "                          <property name=\"name\">8</property>\n       "
  "                         <property name=\"can_focus\">False</property>\n"
  "                                <property name=\"margin_left\">12</prop"
  "erty>\n                                <child>\n                       "
  "           <object class=\"GtkBox\" id=\"box1\">\n                     "
  "               <property name=\"visible\">True</property>\n            "
  "                        <property name=\"can_focus\">False</property>\n"
  "                                    <property name=\"spacing\">18</prop"
  "erty>\n                                    <child>\n                   "
  "                   <object class=\"GtkImage\" id=\"image1\">\n         "
  "                               <property name=\"visible\">True</propert"
  "y>\n                                        <property name=\"can_focus\""
  ">False</property>\n                                        <property na"
  "me=\"icon_name\">dialog-information-symbolic</property>\n              "
  "                          <property name=\"icon_size\">1</property>\n  "
  "                                    </object>\n                        "
  "              <packing>\n                                        <prope"
  "rty name=\"expand\">False</property>\n                                 "
  "       <property name=\"fill\">True</property>\n                       "
  "                 <property name=\"position\">0</property>\n            "
  "                          </packing>\n                                 "
  "   </child>\n                                    <child>\n             "
  "                         <object class=\"GtkLabel\" id=\"label10\">\n  "
  "                                      <property name=\"visible\">True</"
  "property>\n                                        <property name=\"can"
  "_focus\">False</property>\n                                        <pro"
  "perty name=\"label\" translatable=\"yes\">&lt;b&gt;Currently no notific"
  "ations are shown&lt;/b&gt;\nexcept for messages marked as urgent.</prop"
  "erty>\n                                        <property name=\"use_mar"
  "kup\">True</property>\n                                        <propert"
  "y name=\"ellipsize\">end</property>\n                                  "
  "      <property name=\"xalign\">0</property>\n                         "
  "             </object>\n                                      <packing>"
  "\n                                        <property name=\"expand\">Tru"
  "e</property>\n                                        <property name=\""
  "fill\">True</property>\n                                        <proper"
  "ty name=\"position\">1</property>\n                                    "
  "  </packing>\n                                    </child>\n           "
  "                       </object>\n                                  <pa"
  "cking>\n                                    <property name=\"expand\">F"
  "alse</property>\n                                    <property name=\"f"
  "ill\">True</property>\n                                    <property na"
  "me=\"position\">0</property>\n                                  </packi"
  "ng>\n                                </child>\n                        "
  "      </object>\n                              <packing>\n             "
  "                   <property name=\"expand\">False</property>\n        "
  "                        <property name=\"fill\">True</property>\n      "
  "                          <property name=\"position\">0</property>\n   "
  "                           </packing>\n                            </ch"
  "ild>\n                          </object>\n                        </ch"
  "ild>\n                      </object>\n                      <packing>\n"
  "                        <property name=\"left_attach\">0</property>\n  "
  "                      <property name=\"top_attach\">1</property>\n     "
  "                   <property name=\"width\">2</property>\n             "
  "         </packing>\n                    </child>\n                    "
  "<child>\n                      <object class=\"GtkScrolledWindow\" id=\""
  "known_applications_scrolled_window\">\n                        <propert"
  "y name=\"visible\">True</property>\n                        <property n"
  "ame=\"can_focus\">True</property>\n                        <property na"
  "me=\"vexpand\">True</property>\n                        <property name="
  "\"shadow_type\">in</property>\n                      </object>\n       "
  "               <packing>\n                        <property name=\"left"
  "_attach\">0</property>\n                        <property name=\"top_at"
  "tach\">3</property>\n                        <property name=\"width\">2"
  "</property>\n                      </packing>\n                    </ch"
  "ild>\n                  </object>\n                  <packing>\n       "
  "             <property name=\"position\">1</property>\n                "
  "  </packing>\n                </child>\n                <child type=\"t"
  "ab\">\n                  <object class=\"GtkLabel\" id=\"label7\">\n   "
  "                 <property name=\"visible\">True</property>\n          "
  "          <property name=\"can_focus\">False</property>\n              "
  "      <property name=\"label\" translatable=\"yes\">Applications</prope"
  "rty>\n                  </object>\n                  <packing>\n       "
  "             <property name=\"position\">1</property>\n                "
  "    <property name=\"tab_fill\">False</property>\n                  </p"
  "acking>\n                </child>\n              </object>\n           "
  "   <packing>\n                <property name=\"expand\">True</property>"
  "\n                <property name=\"fill\">True</property>\n            "
  "    <property name=\"position\">0</property>\n              </packing>\n"
  "            </child>\n          </object>\n          <packing>\n       "
  "     <property name=\"expand\">True</property>\n            <property n"
  "ame=\"fill\">True</property>\n            <property name=\"position\">1"
  "</property>\n          </packing>\n        </child>\n      </object>\n "
  "   </child>\n    <action-widgets>\n      <action-widget response=\"1\">"
  "close_btn</action-widget>\n    </action-widgets>\n  </object>\n</interf"
  "ace>\n"
};

static const unsigned xfce4_notifyd_config_ui_length = 24538u;

