/*
 * Generated by gdbus-codegen 2.50.0. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "xfce4-notifyd/xfce-notify-gbus.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.freedesktop.Notifications
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:XfceNotifyGBus
 * @title: XfceNotifyGBus
 * @short_description: Generated C code for the org.freedesktop.Notifications D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-freedesktop-Notifications.top_of_page">org.freedesktop.Notifications</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.freedesktop.Notifications ---- */

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_method_info_get_capabilities_OUT_ARG_capabilities =
{
  {
    -1,
    (gchar *) "capabilities",
    (gchar *) "as",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _xfce_notify_gbus_method_info_get_capabilities_OUT_ARG_pointers[] =
{
  &_xfce_notify_gbus_method_info_get_capabilities_OUT_ARG_capabilities,
  NULL
};

static const _ExtendedGDBusMethodInfo _xfce_notify_gbus_method_info_get_capabilities =
{
  {
    -1,
    (gchar *) "GetCapabilities",
    NULL,
    (GDBusArgInfo **) &_xfce_notify_gbus_method_info_get_capabilities_OUT_ARG_pointers,
    NULL
  },
  "handle-get-capabilities",
  FALSE
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_method_info_notify_IN_ARG_app_name =
{
  {
    -1,
    (gchar *) "app_name",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_method_info_notify_IN_ARG_replaces_id =
{
  {
    -1,
    (gchar *) "replaces_id",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_method_info_notify_IN_ARG_app_icon =
{
  {
    -1,
    (gchar *) "app_icon",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_method_info_notify_IN_ARG_summary =
{
  {
    -1,
    (gchar *) "summary",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_method_info_notify_IN_ARG_body =
{
  {
    -1,
    (gchar *) "body",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_method_info_notify_IN_ARG_actions =
{
  {
    -1,
    (gchar *) "actions",
    (gchar *) "as",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_method_info_notify_IN_ARG_hints =
{
  {
    -1,
    (gchar *) "hints",
    (gchar *) "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_method_info_notify_IN_ARG_expire_timeout =
{
  {
    -1,
    (gchar *) "expire_timeout",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _xfce_notify_gbus_method_info_notify_IN_ARG_pointers[] =
{
  &_xfce_notify_gbus_method_info_notify_IN_ARG_app_name,
  &_xfce_notify_gbus_method_info_notify_IN_ARG_replaces_id,
  &_xfce_notify_gbus_method_info_notify_IN_ARG_app_icon,
  &_xfce_notify_gbus_method_info_notify_IN_ARG_summary,
  &_xfce_notify_gbus_method_info_notify_IN_ARG_body,
  &_xfce_notify_gbus_method_info_notify_IN_ARG_actions,
  &_xfce_notify_gbus_method_info_notify_IN_ARG_hints,
  &_xfce_notify_gbus_method_info_notify_IN_ARG_expire_timeout,
  NULL
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_method_info_notify_OUT_ARG_id =
{
  {
    -1,
    (gchar *) "id",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _xfce_notify_gbus_method_info_notify_OUT_ARG_pointers[] =
{
  &_xfce_notify_gbus_method_info_notify_OUT_ARG_id,
  NULL
};

static const _ExtendedGDBusMethodInfo _xfce_notify_gbus_method_info_notify =
{
  {
    -1,
    (gchar *) "Notify",
    (GDBusArgInfo **) &_xfce_notify_gbus_method_info_notify_IN_ARG_pointers,
    (GDBusArgInfo **) &_xfce_notify_gbus_method_info_notify_OUT_ARG_pointers,
    NULL
  },
  "handle-notify",
  FALSE
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_method_info_close_notification_IN_ARG_id =
{
  {
    -1,
    (gchar *) "id",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _xfce_notify_gbus_method_info_close_notification_IN_ARG_pointers[] =
{
  &_xfce_notify_gbus_method_info_close_notification_IN_ARG_id,
  NULL
};

static const _ExtendedGDBusMethodInfo _xfce_notify_gbus_method_info_close_notification =
{
  {
    -1,
    (gchar *) "CloseNotification",
    (GDBusArgInfo **) &_xfce_notify_gbus_method_info_close_notification_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-close-notification",
  FALSE
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_method_info_get_server_information_OUT_ARG_name =
{
  {
    -1,
    (gchar *) "name",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_method_info_get_server_information_OUT_ARG_vendor =
{
  {
    -1,
    (gchar *) "vendor",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_method_info_get_server_information_OUT_ARG_version =
{
  {
    -1,
    (gchar *) "version",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_method_info_get_server_information_OUT_ARG_spec_version =
{
  {
    -1,
    (gchar *) "spec_version",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _xfce_notify_gbus_method_info_get_server_information_OUT_ARG_pointers[] =
{
  &_xfce_notify_gbus_method_info_get_server_information_OUT_ARG_name,
  &_xfce_notify_gbus_method_info_get_server_information_OUT_ARG_vendor,
  &_xfce_notify_gbus_method_info_get_server_information_OUT_ARG_version,
  &_xfce_notify_gbus_method_info_get_server_information_OUT_ARG_spec_version,
  NULL
};

static const _ExtendedGDBusMethodInfo _xfce_notify_gbus_method_info_get_server_information =
{
  {
    -1,
    (gchar *) "GetServerInformation",
    NULL,
    (GDBusArgInfo **) &_xfce_notify_gbus_method_info_get_server_information_OUT_ARG_pointers,
    NULL
  },
  "handle-get-server-information",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _xfce_notify_gbus_method_info_pointers[] =
{
  &_xfce_notify_gbus_method_info_get_capabilities,
  &_xfce_notify_gbus_method_info_notify,
  &_xfce_notify_gbus_method_info_close_notification,
  &_xfce_notify_gbus_method_info_get_server_information,
  NULL
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_signal_info_notification_closed_ARG_id =
{
  {
    -1,
    (gchar *) "id",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_signal_info_notification_closed_ARG_reason =
{
  {
    -1,
    (gchar *) "reason",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _xfce_notify_gbus_signal_info_notification_closed_ARG_pointers[] =
{
  &_xfce_notify_gbus_signal_info_notification_closed_ARG_id,
  &_xfce_notify_gbus_signal_info_notification_closed_ARG_reason,
  NULL
};

static const _ExtendedGDBusSignalInfo _xfce_notify_gbus_signal_info_notification_closed =
{
  {
    -1,
    (gchar *) "NotificationClosed",
    (GDBusArgInfo **) &_xfce_notify_gbus_signal_info_notification_closed_ARG_pointers,
    NULL
  },
  "notification-closed"
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_signal_info_action_invoked_ARG_id =
{
  {
    -1,
    (gchar *) "id",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _xfce_notify_gbus_signal_info_action_invoked_ARG_action_key =
{
  {
    -1,
    (gchar *) "action_key",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _xfce_notify_gbus_signal_info_action_invoked_ARG_pointers[] =
{
  &_xfce_notify_gbus_signal_info_action_invoked_ARG_id,
  &_xfce_notify_gbus_signal_info_action_invoked_ARG_action_key,
  NULL
};

static const _ExtendedGDBusSignalInfo _xfce_notify_gbus_signal_info_action_invoked =
{
  {
    -1,
    (gchar *) "ActionInvoked",
    (GDBusArgInfo **) &_xfce_notify_gbus_signal_info_action_invoked_ARG_pointers,
    NULL
  },
  "action-invoked"
};

static const _ExtendedGDBusSignalInfo * const _xfce_notify_gbus_signal_info_pointers[] =
{
  &_xfce_notify_gbus_signal_info_notification_closed,
  &_xfce_notify_gbus_signal_info_action_invoked,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _xfce_notify_gbus_interface_info =
{
  {
    -1,
    (gchar *) "org.freedesktop.Notifications",
    (GDBusMethodInfo **) &_xfce_notify_gbus_method_info_pointers,
    (GDBusSignalInfo **) &_xfce_notify_gbus_signal_info_pointers,
    NULL,
    NULL
  },
  "gbus",
};


/**
 * xfce_notify_gbus_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-freedesktop-Notifications.top_of_page">org.freedesktop.Notifications</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
xfce_notify_gbus_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_xfce_notify_gbus_interface_info.parent_struct;
}

/**
 * xfce_notify_gbus_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #XfceNotifyGBus interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
xfce_notify_gbus_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * XfceNotifyGBus:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-Notifications.top_of_page">org.freedesktop.Notifications</link>.
 */

/**
 * XfceNotifyGBusIface:
 * @parent_iface: The parent interface.
 * @handle_close_notification: Handler for the #XfceNotifyGBus::handle-close-notification signal.
 * @handle_get_capabilities: Handler for the #XfceNotifyGBus::handle-get-capabilities signal.
 * @handle_get_server_information: Handler for the #XfceNotifyGBus::handle-get-server-information signal.
 * @handle_notify: Handler for the #XfceNotifyGBus::handle-notify signal.
 * @action_invoked: Handler for the #XfceNotifyGBus::action-invoked signal.
 * @notification_closed: Handler for the #XfceNotifyGBus::notification-closed signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-Notifications.top_of_page">org.freedesktop.Notifications</link>.
 */

typedef XfceNotifyGBusIface XfceNotifyGBusInterface;
G_DEFINE_INTERFACE (XfceNotifyGBus, xfce_notify_gbus, G_TYPE_OBJECT);

static void
xfce_notify_gbus_default_init (XfceNotifyGBusIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * XfceNotifyGBus::handle-get-capabilities:
   * @object: A #XfceNotifyGBus.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-Notifications.GetCapabilities">GetCapabilities()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call xfce_notify_gbus_complete_get_capabilities() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-capabilities",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (XfceNotifyGBusIface, handle_get_capabilities),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * XfceNotifyGBus::handle-notify:
   * @object: A #XfceNotifyGBus.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_app_name: Argument passed by remote caller.
   * @arg_replaces_id: Argument passed by remote caller.
   * @arg_app_icon: Argument passed by remote caller.
   * @arg_summary: Argument passed by remote caller.
   * @arg_body: Argument passed by remote caller.
   * @arg_actions: Argument passed by remote caller.
   * @arg_hints: Argument passed by remote caller.
   * @arg_expire_timeout: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-Notifications.Notify">Notify()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call xfce_notify_gbus_complete_notify() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-notify",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (XfceNotifyGBusIface, handle_notify),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    9,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_UINT, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRV, G_TYPE_VARIANT, G_TYPE_INT);

  /**
   * XfceNotifyGBus::handle-close-notification:
   * @object: A #XfceNotifyGBus.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_id: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-Notifications.CloseNotification">CloseNotification()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call xfce_notify_gbus_complete_close_notification() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-close-notification",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (XfceNotifyGBusIface, handle_close_notification),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT);

  /**
   * XfceNotifyGBus::handle-get-server-information:
   * @object: A #XfceNotifyGBus.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-Notifications.GetServerInformation">GetServerInformation()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call xfce_notify_gbus_complete_get_server_information() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-server-information",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (XfceNotifyGBusIface, handle_get_server_information),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /* GObject signals for received D-Bus signals: */
  /**
   * XfceNotifyGBus::notification-closed:
   * @object: A #XfceNotifyGBus.
   * @arg_id: Argument.
   * @arg_reason: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-freedesktop-Notifications.NotificationClosed">"NotificationClosed"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("notification-closed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (XfceNotifyGBusIface, notification_closed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    2, G_TYPE_UINT, G_TYPE_UINT);

  /**
   * XfceNotifyGBus::action-invoked:
   * @object: A #XfceNotifyGBus.
   * @arg_id: Argument.
   * @arg_action_key: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-freedesktop-Notifications.ActionInvoked">"ActionInvoked"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("action-invoked",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (XfceNotifyGBusIface, action_invoked),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    2, G_TYPE_UINT, G_TYPE_STRING);

}

/**
 * xfce_notify_gbus_emit_notification_closed:
 * @object: A #XfceNotifyGBus.
 * @arg_id: Argument to pass with the signal.
 * @arg_reason: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-freedesktop-Notifications.NotificationClosed">"NotificationClosed"</link> D-Bus signal.
 */
void
xfce_notify_gbus_emit_notification_closed (
    XfceNotifyGBus *object,
    guint arg_id,
    guint arg_reason)
{
  g_signal_emit_by_name (object, "notification-closed", arg_id, arg_reason);
}

/**
 * xfce_notify_gbus_emit_action_invoked:
 * @object: A #XfceNotifyGBus.
 * @arg_id: Argument to pass with the signal.
 * @arg_action_key: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-freedesktop-Notifications.ActionInvoked">"ActionInvoked"</link> D-Bus signal.
 */
void
xfce_notify_gbus_emit_action_invoked (
    XfceNotifyGBus *object,
    guint arg_id,
    const gchar *arg_action_key)
{
  g_signal_emit_by_name (object, "action-invoked", arg_id, arg_action_key);
}

/**
 * xfce_notify_gbus_call_get_capabilities:
 * @proxy: A #XfceNotifyGBusProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-Notifications.GetCapabilities">GetCapabilities()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call xfce_notify_gbus_call_get_capabilities_finish() to get the result of the operation.
 *
 * See xfce_notify_gbus_call_get_capabilities_sync() for the synchronous, blocking version of this method.
 */
void
xfce_notify_gbus_call_get_capabilities (
    XfceNotifyGBus *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetCapabilities",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * xfce_notify_gbus_call_get_capabilities_finish:
 * @proxy: A #XfceNotifyGBusProxy.
 * @out_capabilities: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to xfce_notify_gbus_call_get_capabilities().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with xfce_notify_gbus_call_get_capabilities().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
xfce_notify_gbus_call_get_capabilities_finish (
    XfceNotifyGBus *proxy,
    gchar ***out_capabilities,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^as)",
                 out_capabilities);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * xfce_notify_gbus_call_get_capabilities_sync:
 * @proxy: A #XfceNotifyGBusProxy.
 * @out_capabilities: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-Notifications.GetCapabilities">GetCapabilities()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See xfce_notify_gbus_call_get_capabilities() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
xfce_notify_gbus_call_get_capabilities_sync (
    XfceNotifyGBus *proxy,
    gchar ***out_capabilities,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetCapabilities",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^as)",
                 out_capabilities);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * xfce_notify_gbus_call_notify:
 * @proxy: A #XfceNotifyGBusProxy.
 * @arg_app_name: Argument to pass with the method invocation.
 * @arg_replaces_id: Argument to pass with the method invocation.
 * @arg_app_icon: Argument to pass with the method invocation.
 * @arg_summary: Argument to pass with the method invocation.
 * @arg_body: Argument to pass with the method invocation.
 * @arg_actions: Argument to pass with the method invocation.
 * @arg_hints: Argument to pass with the method invocation.
 * @arg_expire_timeout: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-Notifications.Notify">Notify()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call xfce_notify_gbus_call_notify_finish() to get the result of the operation.
 *
 * See xfce_notify_gbus_call_notify_sync() for the synchronous, blocking version of this method.
 */
void
xfce_notify_gbus_call_notify (
    XfceNotifyGBus *proxy,
    const gchar *arg_app_name,
    guint arg_replaces_id,
    const gchar *arg_app_icon,
    const gchar *arg_summary,
    const gchar *arg_body,
    const gchar *const *arg_actions,
    GVariant *arg_hints,
    gint arg_expire_timeout,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Notify",
    g_variant_new ("(susss^as@a{sv}i)",
                   arg_app_name,
                   arg_replaces_id,
                   arg_app_icon,
                   arg_summary,
                   arg_body,
                   arg_actions,
                   arg_hints,
                   arg_expire_timeout),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * xfce_notify_gbus_call_notify_finish:
 * @proxy: A #XfceNotifyGBusProxy.
 * @out_id: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to xfce_notify_gbus_call_notify().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with xfce_notify_gbus_call_notify().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
xfce_notify_gbus_call_notify_finish (
    XfceNotifyGBus *proxy,
    guint *out_id,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_id);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * xfce_notify_gbus_call_notify_sync:
 * @proxy: A #XfceNotifyGBusProxy.
 * @arg_app_name: Argument to pass with the method invocation.
 * @arg_replaces_id: Argument to pass with the method invocation.
 * @arg_app_icon: Argument to pass with the method invocation.
 * @arg_summary: Argument to pass with the method invocation.
 * @arg_body: Argument to pass with the method invocation.
 * @arg_actions: Argument to pass with the method invocation.
 * @arg_hints: Argument to pass with the method invocation.
 * @arg_expire_timeout: Argument to pass with the method invocation.
 * @out_id: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-Notifications.Notify">Notify()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See xfce_notify_gbus_call_notify() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
xfce_notify_gbus_call_notify_sync (
    XfceNotifyGBus *proxy,
    const gchar *arg_app_name,
    guint arg_replaces_id,
    const gchar *arg_app_icon,
    const gchar *arg_summary,
    const gchar *arg_body,
    const gchar *const *arg_actions,
    GVariant *arg_hints,
    gint arg_expire_timeout,
    guint *out_id,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Notify",
    g_variant_new ("(susss^as@a{sv}i)",
                   arg_app_name,
                   arg_replaces_id,
                   arg_app_icon,
                   arg_summary,
                   arg_body,
                   arg_actions,
                   arg_hints,
                   arg_expire_timeout),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_id);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * xfce_notify_gbus_call_close_notification:
 * @proxy: A #XfceNotifyGBusProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-Notifications.CloseNotification">CloseNotification()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call xfce_notify_gbus_call_close_notification_finish() to get the result of the operation.
 *
 * See xfce_notify_gbus_call_close_notification_sync() for the synchronous, blocking version of this method.
 */
void
xfce_notify_gbus_call_close_notification (
    XfceNotifyGBus *proxy,
    guint arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "CloseNotification",
    g_variant_new ("(u)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * xfce_notify_gbus_call_close_notification_finish:
 * @proxy: A #XfceNotifyGBusProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to xfce_notify_gbus_call_close_notification().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with xfce_notify_gbus_call_close_notification().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
xfce_notify_gbus_call_close_notification_finish (
    XfceNotifyGBus *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * xfce_notify_gbus_call_close_notification_sync:
 * @proxy: A #XfceNotifyGBusProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-Notifications.CloseNotification">CloseNotification()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See xfce_notify_gbus_call_close_notification() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
xfce_notify_gbus_call_close_notification_sync (
    XfceNotifyGBus *proxy,
    guint arg_id,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "CloseNotification",
    g_variant_new ("(u)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * xfce_notify_gbus_call_get_server_information:
 * @proxy: A #XfceNotifyGBusProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-Notifications.GetServerInformation">GetServerInformation()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call xfce_notify_gbus_call_get_server_information_finish() to get the result of the operation.
 *
 * See xfce_notify_gbus_call_get_server_information_sync() for the synchronous, blocking version of this method.
 */
void
xfce_notify_gbus_call_get_server_information (
    XfceNotifyGBus *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetServerInformation",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * xfce_notify_gbus_call_get_server_information_finish:
 * @proxy: A #XfceNotifyGBusProxy.
 * @out_name: (out): Return location for return parameter or %NULL to ignore.
 * @out_vendor: (out): Return location for return parameter or %NULL to ignore.
 * @out_version: (out): Return location for return parameter or %NULL to ignore.
 * @out_spec_version: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to xfce_notify_gbus_call_get_server_information().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with xfce_notify_gbus_call_get_server_information().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
xfce_notify_gbus_call_get_server_information_finish (
    XfceNotifyGBus *proxy,
    gchar **out_name,
    gchar **out_vendor,
    gchar **out_version,
    gchar **out_spec_version,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(ssss)",
                 out_name,
                 out_vendor,
                 out_version,
                 out_spec_version);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * xfce_notify_gbus_call_get_server_information_sync:
 * @proxy: A #XfceNotifyGBusProxy.
 * @out_name: (out): Return location for return parameter or %NULL to ignore.
 * @out_vendor: (out): Return location for return parameter or %NULL to ignore.
 * @out_version: (out): Return location for return parameter or %NULL to ignore.
 * @out_spec_version: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-Notifications.GetServerInformation">GetServerInformation()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See xfce_notify_gbus_call_get_server_information() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
xfce_notify_gbus_call_get_server_information_sync (
    XfceNotifyGBus *proxy,
    gchar **out_name,
    gchar **out_vendor,
    gchar **out_version,
    gchar **out_spec_version,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetServerInformation",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(ssss)",
                 out_name,
                 out_vendor,
                 out_version,
                 out_spec_version);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * xfce_notify_gbus_complete_get_capabilities:
 * @object: A #XfceNotifyGBus.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @capabilities: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-Notifications.GetCapabilities">GetCapabilities()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
xfce_notify_gbus_complete_get_capabilities (
    XfceNotifyGBus *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *capabilities)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(^as)",
                   capabilities));
}

/**
 * xfce_notify_gbus_complete_notify:
 * @object: A #XfceNotifyGBus.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @id: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-Notifications.Notify">Notify()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
xfce_notify_gbus_complete_notify (
    XfceNotifyGBus *object,
    GDBusMethodInvocation *invocation,
    guint id)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(u)",
                   id));
}

/**
 * xfce_notify_gbus_complete_close_notification:
 * @object: A #XfceNotifyGBus.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-Notifications.CloseNotification">CloseNotification()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
xfce_notify_gbus_complete_close_notification (
    XfceNotifyGBus *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * xfce_notify_gbus_complete_get_server_information:
 * @object: A #XfceNotifyGBus.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @name: Parameter to return.
 * @vendor: Parameter to return.
 * @version: Parameter to return.
 * @spec_version: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-Notifications.GetServerInformation">GetServerInformation()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
xfce_notify_gbus_complete_get_server_information (
    XfceNotifyGBus *object,
    GDBusMethodInvocation *invocation,
    const gchar *name,
    const gchar *vendor,
    const gchar *version,
    const gchar *spec_version)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(ssss)",
                   name,
                   vendor,
                   version,
                   spec_version));
}

/* ------------------------------------------------------------------------ */

/**
 * XfceNotifyGBusProxy:
 *
 * The #XfceNotifyGBusProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * XfceNotifyGBusProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #XfceNotifyGBusProxy.
 */

struct _XfceNotifyGBusProxyPrivate
{
  GData *qdata;
};

static void xfce_notify_gbus_proxy_iface_init (XfceNotifyGBusIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (XfceNotifyGBusProxy, xfce_notify_gbus_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (XfceNotifyGBusProxy)
                         G_IMPLEMENT_INTERFACE (XFCE_NOTIFY_TYPE_GBUS, xfce_notify_gbus_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (XfceNotifyGBusProxy, xfce_notify_gbus_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (XFCE_NOTIFY_TYPE_GBUS, xfce_notify_gbus_proxy_iface_init));

#endif
static void
xfce_notify_gbus_proxy_finalize (GObject *object)
{
  XfceNotifyGBusProxy *proxy = XFCE_NOTIFY_GBUS_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (xfce_notify_gbus_proxy_parent_class)->finalize (object);
}

static void
xfce_notify_gbus_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
xfce_notify_gbus_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
xfce_notify_gbus_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_xfce_notify_gbus_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], XFCE_NOTIFY_TYPE_GBUS);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, XFCE_NOTIFY_TYPE_GBUS);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
xfce_notify_gbus_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  XfceNotifyGBusProxy *proxy = XFCE_NOTIFY_GBUS_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_xfce_notify_gbus_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_xfce_notify_gbus_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
xfce_notify_gbus_proxy_init (XfceNotifyGBusProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = xfce_notify_gbus_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, XFCE_NOTIFY_TYPE_GBUS_PROXY, XfceNotifyGBusProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), xfce_notify_gbus_interface_info ());
}

static void
xfce_notify_gbus_proxy_class_init (XfceNotifyGBusProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = xfce_notify_gbus_proxy_finalize;
  gobject_class->get_property = xfce_notify_gbus_proxy_get_property;
  gobject_class->set_property = xfce_notify_gbus_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = xfce_notify_gbus_proxy_g_signal;
  proxy_class->g_properties_changed = xfce_notify_gbus_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (XfceNotifyGBusProxyPrivate));
#endif
}

static void
xfce_notify_gbus_proxy_iface_init (XfceNotifyGBusIface *iface)
{
}

/**
 * xfce_notify_gbus_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-Notifications.top_of_page">org.freedesktop.Notifications</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call xfce_notify_gbus_proxy_new_finish() to get the result of the operation.
 *
 * See xfce_notify_gbus_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
xfce_notify_gbus_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (XFCE_NOTIFY_TYPE_GBUS_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.Notifications", NULL);
}

/**
 * xfce_notify_gbus_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to xfce_notify_gbus_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with xfce_notify_gbus_proxy_new().
 *
 * Returns: (transfer full) (type XfceNotifyGBusProxy): The constructed proxy object or %NULL if @error is set.
 */
XfceNotifyGBus *
xfce_notify_gbus_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return XFCE_NOTIFY_GBUS (ret);
  else
    return NULL;
}

/**
 * xfce_notify_gbus_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-Notifications.top_of_page">org.freedesktop.Notifications</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See xfce_notify_gbus_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type XfceNotifyGBusProxy): The constructed proxy object or %NULL if @error is set.
 */
XfceNotifyGBus *
xfce_notify_gbus_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (XFCE_NOTIFY_TYPE_GBUS_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.Notifications", NULL);
  if (ret != NULL)
    return XFCE_NOTIFY_GBUS (ret);
  else
    return NULL;
}


/**
 * xfce_notify_gbus_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like xfce_notify_gbus_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call xfce_notify_gbus_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See xfce_notify_gbus_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
xfce_notify_gbus_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (XFCE_NOTIFY_TYPE_GBUS_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.Notifications", NULL);
}

/**
 * xfce_notify_gbus_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to xfce_notify_gbus_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with xfce_notify_gbus_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type XfceNotifyGBusProxy): The constructed proxy object or %NULL if @error is set.
 */
XfceNotifyGBus *
xfce_notify_gbus_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return XFCE_NOTIFY_GBUS (ret);
  else
    return NULL;
}

/**
 * xfce_notify_gbus_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like xfce_notify_gbus_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See xfce_notify_gbus_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type XfceNotifyGBusProxy): The constructed proxy object or %NULL if @error is set.
 */
XfceNotifyGBus *
xfce_notify_gbus_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (XFCE_NOTIFY_TYPE_GBUS_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.Notifications", NULL);
  if (ret != NULL)
    return XFCE_NOTIFY_GBUS (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * XfceNotifyGBusSkeleton:
 *
 * The #XfceNotifyGBusSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * XfceNotifyGBusSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #XfceNotifyGBusSkeleton.
 */

struct _XfceNotifyGBusSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_xfce_notify_gbus_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  XfceNotifyGBusSkeleton *skeleton = XFCE_NOTIFY_GBUS_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], XFCE_NOTIFY_TYPE_GBUS);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, XFCE_NOTIFY_TYPE_GBUS);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_xfce_notify_gbus_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  XfceNotifyGBusSkeleton *skeleton = XFCE_NOTIFY_GBUS_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_xfce_notify_gbus_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_xfce_notify_gbus_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  XfceNotifyGBusSkeleton *skeleton = XFCE_NOTIFY_GBUS_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_xfce_notify_gbus_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _xfce_notify_gbus_skeleton_vtable =
{
  _xfce_notify_gbus_skeleton_handle_method_call,
  _xfce_notify_gbus_skeleton_handle_get_property,
  _xfce_notify_gbus_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
xfce_notify_gbus_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return xfce_notify_gbus_interface_info ();
}

static GDBusInterfaceVTable *
xfce_notify_gbus_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_xfce_notify_gbus_skeleton_vtable;
}

static GVariant *
xfce_notify_gbus_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  XfceNotifyGBusSkeleton *skeleton = XFCE_NOTIFY_GBUS_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_xfce_notify_gbus_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _xfce_notify_gbus_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _xfce_notify_gbus_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _xfce_notify_gbus_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.Notifications", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
xfce_notify_gbus_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_xfce_notify_gbus_on_signal_notification_closed (
    XfceNotifyGBus *object,
    guint arg_id,
    guint arg_reason)
{
  XfceNotifyGBusSkeleton *skeleton = XFCE_NOTIFY_GBUS_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(uu)",
                   arg_id,
                   arg_reason));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.Notifications", "NotificationClosed",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_xfce_notify_gbus_on_signal_action_invoked (
    XfceNotifyGBus *object,
    guint arg_id,
    const gchar *arg_action_key)
{
  XfceNotifyGBusSkeleton *skeleton = XFCE_NOTIFY_GBUS_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(us)",
                   arg_id,
                   arg_action_key));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.Notifications", "ActionInvoked",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void xfce_notify_gbus_skeleton_iface_init (XfceNotifyGBusIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (XfceNotifyGBusSkeleton, xfce_notify_gbus_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (XfceNotifyGBusSkeleton)
                         G_IMPLEMENT_INTERFACE (XFCE_NOTIFY_TYPE_GBUS, xfce_notify_gbus_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (XfceNotifyGBusSkeleton, xfce_notify_gbus_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (XFCE_NOTIFY_TYPE_GBUS, xfce_notify_gbus_skeleton_iface_init));

#endif
static void
xfce_notify_gbus_skeleton_finalize (GObject *object)
{
  XfceNotifyGBusSkeleton *skeleton = XFCE_NOTIFY_GBUS_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (xfce_notify_gbus_skeleton_parent_class)->finalize (object);
}

static void
xfce_notify_gbus_skeleton_init (XfceNotifyGBusSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = xfce_notify_gbus_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, XFCE_NOTIFY_TYPE_GBUS_SKELETON, XfceNotifyGBusSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
xfce_notify_gbus_skeleton_class_init (XfceNotifyGBusSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = xfce_notify_gbus_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = xfce_notify_gbus_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = xfce_notify_gbus_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = xfce_notify_gbus_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = xfce_notify_gbus_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (XfceNotifyGBusSkeletonPrivate));
#endif
}

static void
xfce_notify_gbus_skeleton_iface_init (XfceNotifyGBusIface *iface)
{
  iface->notification_closed = _xfce_notify_gbus_on_signal_notification_closed;
  iface->action_invoked = _xfce_notify_gbus_on_signal_action_invoked;
}

/**
 * xfce_notify_gbus_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-Notifications.top_of_page">org.freedesktop.Notifications</link>.
 *
 * Returns: (transfer full) (type XfceNotifyGBusSkeleton): The skeleton object.
 */
XfceNotifyGBus *
xfce_notify_gbus_skeleton_new (void)
{
  return XFCE_NOTIFY_GBUS (g_object_new (XFCE_NOTIFY_TYPE_GBUS_SKELETON, NULL));
}

/* ------------------------------------------------------------------------
 * Code for interface org.xfce.Notifyd
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:XfceNotifyOrgXfceNotifyd
 * @title: XfceNotifyOrgXfceNotifyd
 * @short_description: Generated C code for the org.xfce.Notifyd D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-xfce-Notifyd.top_of_page">org.xfce.Notifyd</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.xfce.Notifyd ---- */

static const _ExtendedGDBusMethodInfo _xfce_notify_org_xfce_notifyd_method_info_quit =
{
  {
    -1,
    (gchar *) "Quit",
    NULL,
    NULL,
    NULL
  },
  "handle-quit",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _xfce_notify_org_xfce_notifyd_method_info_pointers[] =
{
  &_xfce_notify_org_xfce_notifyd_method_info_quit,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _xfce_notify_org_xfce_notifyd_interface_info =
{
  {
    -1,
    (gchar *) "org.xfce.Notifyd",
    (GDBusMethodInfo **) &_xfce_notify_org_xfce_notifyd_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "org-xfce-notifyd",
};


/**
 * xfce_notify_org_xfce_notifyd_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-xfce-Notifyd.top_of_page">org.xfce.Notifyd</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
xfce_notify_org_xfce_notifyd_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_xfce_notify_org_xfce_notifyd_interface_info.parent_struct;
}

/**
 * xfce_notify_org_xfce_notifyd_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #XfceNotifyOrgXfceNotifyd interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
xfce_notify_org_xfce_notifyd_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * XfceNotifyOrgXfceNotifyd:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-xfce-Notifyd.top_of_page">org.xfce.Notifyd</link>.
 */

/**
 * XfceNotifyOrgXfceNotifydIface:
 * @parent_iface: The parent interface.
 * @handle_quit: Handler for the #XfceNotifyOrgXfceNotifyd::handle-quit signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-xfce-Notifyd.top_of_page">org.xfce.Notifyd</link>.
 */

typedef XfceNotifyOrgXfceNotifydIface XfceNotifyOrgXfceNotifydInterface;
G_DEFINE_INTERFACE (XfceNotifyOrgXfceNotifyd, xfce_notify_org_xfce_notifyd, G_TYPE_OBJECT);

static void
xfce_notify_org_xfce_notifyd_default_init (XfceNotifyOrgXfceNotifydIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * XfceNotifyOrgXfceNotifyd::handle-quit:
   * @object: A #XfceNotifyOrgXfceNotifyd.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-xfce-Notifyd.Quit">Quit()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call xfce_notify_org_xfce_notifyd_complete_quit() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-quit",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (XfceNotifyOrgXfceNotifydIface, handle_quit),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

}

/**
 * xfce_notify_org_xfce_notifyd_call_quit:
 * @proxy: A #XfceNotifyOrgXfceNotifydProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-xfce-Notifyd.Quit">Quit()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call xfce_notify_org_xfce_notifyd_call_quit_finish() to get the result of the operation.
 *
 * See xfce_notify_org_xfce_notifyd_call_quit_sync() for the synchronous, blocking version of this method.
 */
void
xfce_notify_org_xfce_notifyd_call_quit (
    XfceNotifyOrgXfceNotifyd *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Quit",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * xfce_notify_org_xfce_notifyd_call_quit_finish:
 * @proxy: A #XfceNotifyOrgXfceNotifydProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to xfce_notify_org_xfce_notifyd_call_quit().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with xfce_notify_org_xfce_notifyd_call_quit().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
xfce_notify_org_xfce_notifyd_call_quit_finish (
    XfceNotifyOrgXfceNotifyd *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * xfce_notify_org_xfce_notifyd_call_quit_sync:
 * @proxy: A #XfceNotifyOrgXfceNotifydProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-xfce-Notifyd.Quit">Quit()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See xfce_notify_org_xfce_notifyd_call_quit() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
xfce_notify_org_xfce_notifyd_call_quit_sync (
    XfceNotifyOrgXfceNotifyd *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Quit",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * xfce_notify_org_xfce_notifyd_complete_quit:
 * @object: A #XfceNotifyOrgXfceNotifyd.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-xfce-Notifyd.Quit">Quit()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
xfce_notify_org_xfce_notifyd_complete_quit (
    XfceNotifyOrgXfceNotifyd *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * XfceNotifyOrgXfceNotifydProxy:
 *
 * The #XfceNotifyOrgXfceNotifydProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * XfceNotifyOrgXfceNotifydProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #XfceNotifyOrgXfceNotifydProxy.
 */

struct _XfceNotifyOrgXfceNotifydProxyPrivate
{
  GData *qdata;
};

static void xfce_notify_org_xfce_notifyd_proxy_iface_init (XfceNotifyOrgXfceNotifydIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (XfceNotifyOrgXfceNotifydProxy, xfce_notify_org_xfce_notifyd_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (XfceNotifyOrgXfceNotifydProxy)
                         G_IMPLEMENT_INTERFACE (XFCE_NOTIFY_TYPE_ORG_XFCE_NOTIFYD, xfce_notify_org_xfce_notifyd_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (XfceNotifyOrgXfceNotifydProxy, xfce_notify_org_xfce_notifyd_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (XFCE_NOTIFY_TYPE_ORG_XFCE_NOTIFYD, xfce_notify_org_xfce_notifyd_proxy_iface_init));

#endif
static void
xfce_notify_org_xfce_notifyd_proxy_finalize (GObject *object)
{
  XfceNotifyOrgXfceNotifydProxy *proxy = XFCE_NOTIFY_ORG_XFCE_NOTIFYD_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (xfce_notify_org_xfce_notifyd_proxy_parent_class)->finalize (object);
}

static void
xfce_notify_org_xfce_notifyd_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
xfce_notify_org_xfce_notifyd_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
xfce_notify_org_xfce_notifyd_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_xfce_notify_org_xfce_notifyd_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], XFCE_NOTIFY_TYPE_ORG_XFCE_NOTIFYD);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, XFCE_NOTIFY_TYPE_ORG_XFCE_NOTIFYD);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
xfce_notify_org_xfce_notifyd_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  XfceNotifyOrgXfceNotifydProxy *proxy = XFCE_NOTIFY_ORG_XFCE_NOTIFYD_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_xfce_notify_org_xfce_notifyd_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_xfce_notify_org_xfce_notifyd_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
xfce_notify_org_xfce_notifyd_proxy_init (XfceNotifyOrgXfceNotifydProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = xfce_notify_org_xfce_notifyd_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, XFCE_NOTIFY_TYPE_ORG_XFCE_NOTIFYD_PROXY, XfceNotifyOrgXfceNotifydProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), xfce_notify_org_xfce_notifyd_interface_info ());
}

static void
xfce_notify_org_xfce_notifyd_proxy_class_init (XfceNotifyOrgXfceNotifydProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = xfce_notify_org_xfce_notifyd_proxy_finalize;
  gobject_class->get_property = xfce_notify_org_xfce_notifyd_proxy_get_property;
  gobject_class->set_property = xfce_notify_org_xfce_notifyd_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = xfce_notify_org_xfce_notifyd_proxy_g_signal;
  proxy_class->g_properties_changed = xfce_notify_org_xfce_notifyd_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (XfceNotifyOrgXfceNotifydProxyPrivate));
#endif
}

static void
xfce_notify_org_xfce_notifyd_proxy_iface_init (XfceNotifyOrgXfceNotifydIface *iface)
{
}

/**
 * xfce_notify_org_xfce_notifyd_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-xfce-Notifyd.top_of_page">org.xfce.Notifyd</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call xfce_notify_org_xfce_notifyd_proxy_new_finish() to get the result of the operation.
 *
 * See xfce_notify_org_xfce_notifyd_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
xfce_notify_org_xfce_notifyd_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (XFCE_NOTIFY_TYPE_ORG_XFCE_NOTIFYD_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.xfce.Notifyd", NULL);
}

/**
 * xfce_notify_org_xfce_notifyd_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to xfce_notify_org_xfce_notifyd_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with xfce_notify_org_xfce_notifyd_proxy_new().
 *
 * Returns: (transfer full) (type XfceNotifyOrgXfceNotifydProxy): The constructed proxy object or %NULL if @error is set.
 */
XfceNotifyOrgXfceNotifyd *
xfce_notify_org_xfce_notifyd_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return XFCE_NOTIFY_ORG_XFCE_NOTIFYD (ret);
  else
    return NULL;
}

/**
 * xfce_notify_org_xfce_notifyd_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-xfce-Notifyd.top_of_page">org.xfce.Notifyd</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See xfce_notify_org_xfce_notifyd_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type XfceNotifyOrgXfceNotifydProxy): The constructed proxy object or %NULL if @error is set.
 */
XfceNotifyOrgXfceNotifyd *
xfce_notify_org_xfce_notifyd_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (XFCE_NOTIFY_TYPE_ORG_XFCE_NOTIFYD_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.xfce.Notifyd", NULL);
  if (ret != NULL)
    return XFCE_NOTIFY_ORG_XFCE_NOTIFYD (ret);
  else
    return NULL;
}


/**
 * xfce_notify_org_xfce_notifyd_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like xfce_notify_org_xfce_notifyd_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call xfce_notify_org_xfce_notifyd_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See xfce_notify_org_xfce_notifyd_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
xfce_notify_org_xfce_notifyd_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (XFCE_NOTIFY_TYPE_ORG_XFCE_NOTIFYD_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.xfce.Notifyd", NULL);
}

/**
 * xfce_notify_org_xfce_notifyd_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to xfce_notify_org_xfce_notifyd_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with xfce_notify_org_xfce_notifyd_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type XfceNotifyOrgXfceNotifydProxy): The constructed proxy object or %NULL if @error is set.
 */
XfceNotifyOrgXfceNotifyd *
xfce_notify_org_xfce_notifyd_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return XFCE_NOTIFY_ORG_XFCE_NOTIFYD (ret);
  else
    return NULL;
}

/**
 * xfce_notify_org_xfce_notifyd_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like xfce_notify_org_xfce_notifyd_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See xfce_notify_org_xfce_notifyd_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type XfceNotifyOrgXfceNotifydProxy): The constructed proxy object or %NULL if @error is set.
 */
XfceNotifyOrgXfceNotifyd *
xfce_notify_org_xfce_notifyd_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (XFCE_NOTIFY_TYPE_ORG_XFCE_NOTIFYD_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.xfce.Notifyd", NULL);
  if (ret != NULL)
    return XFCE_NOTIFY_ORG_XFCE_NOTIFYD (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * XfceNotifyOrgXfceNotifydSkeleton:
 *
 * The #XfceNotifyOrgXfceNotifydSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * XfceNotifyOrgXfceNotifydSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #XfceNotifyOrgXfceNotifydSkeleton.
 */

struct _XfceNotifyOrgXfceNotifydSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_xfce_notify_org_xfce_notifyd_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  XfceNotifyOrgXfceNotifydSkeleton *skeleton = XFCE_NOTIFY_ORG_XFCE_NOTIFYD_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], XFCE_NOTIFY_TYPE_ORG_XFCE_NOTIFYD);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, XFCE_NOTIFY_TYPE_ORG_XFCE_NOTIFYD);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_xfce_notify_org_xfce_notifyd_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  XfceNotifyOrgXfceNotifydSkeleton *skeleton = XFCE_NOTIFY_ORG_XFCE_NOTIFYD_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_xfce_notify_org_xfce_notifyd_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_xfce_notify_org_xfce_notifyd_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  XfceNotifyOrgXfceNotifydSkeleton *skeleton = XFCE_NOTIFY_ORG_XFCE_NOTIFYD_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_xfce_notify_org_xfce_notifyd_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _xfce_notify_org_xfce_notifyd_skeleton_vtable =
{
  _xfce_notify_org_xfce_notifyd_skeleton_handle_method_call,
  _xfce_notify_org_xfce_notifyd_skeleton_handle_get_property,
  _xfce_notify_org_xfce_notifyd_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
xfce_notify_org_xfce_notifyd_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return xfce_notify_org_xfce_notifyd_interface_info ();
}

static GDBusInterfaceVTable *
xfce_notify_org_xfce_notifyd_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_xfce_notify_org_xfce_notifyd_skeleton_vtable;
}

static GVariant *
xfce_notify_org_xfce_notifyd_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  XfceNotifyOrgXfceNotifydSkeleton *skeleton = XFCE_NOTIFY_ORG_XFCE_NOTIFYD_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_xfce_notify_org_xfce_notifyd_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _xfce_notify_org_xfce_notifyd_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _xfce_notify_org_xfce_notifyd_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _xfce_notify_org_xfce_notifyd_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.xfce.Notifyd", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
xfce_notify_org_xfce_notifyd_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void xfce_notify_org_xfce_notifyd_skeleton_iface_init (XfceNotifyOrgXfceNotifydIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (XfceNotifyOrgXfceNotifydSkeleton, xfce_notify_org_xfce_notifyd_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (XfceNotifyOrgXfceNotifydSkeleton)
                         G_IMPLEMENT_INTERFACE (XFCE_NOTIFY_TYPE_ORG_XFCE_NOTIFYD, xfce_notify_org_xfce_notifyd_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (XfceNotifyOrgXfceNotifydSkeleton, xfce_notify_org_xfce_notifyd_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (XFCE_NOTIFY_TYPE_ORG_XFCE_NOTIFYD, xfce_notify_org_xfce_notifyd_skeleton_iface_init));

#endif
static void
xfce_notify_org_xfce_notifyd_skeleton_finalize (GObject *object)
{
  XfceNotifyOrgXfceNotifydSkeleton *skeleton = XFCE_NOTIFY_ORG_XFCE_NOTIFYD_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (xfce_notify_org_xfce_notifyd_skeleton_parent_class)->finalize (object);
}

static void
xfce_notify_org_xfce_notifyd_skeleton_init (XfceNotifyOrgXfceNotifydSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = xfce_notify_org_xfce_notifyd_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, XFCE_NOTIFY_TYPE_ORG_XFCE_NOTIFYD_SKELETON, XfceNotifyOrgXfceNotifydSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
xfce_notify_org_xfce_notifyd_skeleton_class_init (XfceNotifyOrgXfceNotifydSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = xfce_notify_org_xfce_notifyd_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = xfce_notify_org_xfce_notifyd_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = xfce_notify_org_xfce_notifyd_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = xfce_notify_org_xfce_notifyd_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = xfce_notify_org_xfce_notifyd_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (XfceNotifyOrgXfceNotifydSkeletonPrivate));
#endif
}

static void
xfce_notify_org_xfce_notifyd_skeleton_iface_init (XfceNotifyOrgXfceNotifydIface *iface)
{
}

/**
 * xfce_notify_org_xfce_notifyd_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-xfce-Notifyd.top_of_page">org.xfce.Notifyd</link>.
 *
 * Returns: (transfer full) (type XfceNotifyOrgXfceNotifydSkeleton): The skeleton object.
 */
XfceNotifyOrgXfceNotifyd *
xfce_notify_org_xfce_notifyd_skeleton_new (void)
{
  return XFCE_NOTIFY_ORG_XFCE_NOTIFYD (g_object_new (XFCE_NOTIFY_TYPE_ORG_XFCE_NOTIFYD_SKELETON, NULL));
}

